### ISSUE TITLE
Can not compile on Ubuntu 18.04.3 LTS.

### ISSUE THREAD

**Issue by Csokis** [mywave82/opencubicplayer#4]
I can't compile on Ubuntu 18.04.3 LTS. :(

> gcc -I/opt/local/include -fPIC -Wall -I.././ -D_GNU_SOURCE=1 -D_REENTRANT -I/usr/include/SDL poutput-sdl.c -o poutput-sdl.o -c
poutput-sdl.c: In function ‘set_state_textmode’:
poutput-sdl.c:149:2: warning: #warning TODO, is this right? [-Wcpp]
 #warning TODO, is this right?
  ^~~~~~~
poutput-sdl.c: In function ‘plSetTextMode’:
poutput-sdl.c:258:2: warning: #warning TODO, is this right? [-Wcpp]
 #warning TODO, is this right?
  ^~~~~~~
poutput-sdl.c:269:2: warning: #warning We have disabled textmode being able to change resolution of Screen [-Wcpp]
 #warning We have disabled textmode being able to change resolution of Screen
  ^~~~~~~
poutput-sdl.c: In function ‘set_state_graphmode’:
poutput-sdl.c:309:2: warning: #warning TODO, is this right? [-Wcpp]
 #warning TODO, is this right?
  ^~~~~~~
gcc -I/opt/local/include -fPIC -Wall -I.././ -D_REENTRANT -I/usr/include/SDL2 poutput-sdl2.c -o poutput-sdl2.o -c
gcc -I/opt/local/include -fPIC -Wall -I.././ -shared  -o poutput.so console.o poutput-curses.o poutput-vcsa.o poutput-fb.o poutput-keyboard.o pfonts.o poutput.o poutput-x11.o x11-common.o poutput-sdl.o poutput-sdl2.o -lncursesw -ltinfo  -lXxf86vm -lXext -lXpm -lX11 -L/usr/X11R6/lib -lSDL -lSDL2
poutput-sdl2.o:(.rodata+0x50): multiple definition of `FontSizeInfo'
poutput-sdl.o:(.rodata+0x50): first defined here
poutput-sdl2.o:(.data+0x460): multiple definition of `translate'
poutput-sdl.o:(.data+0x360): first defined here
poutput-sdl2.o:(.data+0x8a0): multiple definition of `translate_shift'
poutput-sdl.o:(.data+0x7a0): first defined here
poutput-sdl2.o:(.data+0x980): multiple definition of `translate_ctrl'
poutput-sdl.o:(.data+0x880): first defined here
poutput-sdl2.o:(.data+0xa60): multiple definition of `translate_alt'
poutput-sdl.o:(.data+0x960): first defined here
collect2: error: ld returned 1 exit status
Makefile:37: recipe for target 'poutput.so' failed
make[1]: *** [poutput.so] Error 1
make[1]: Leaving directory '/mnt/minden/Sources/opencubicplayer/stuff'
Makefile:141: recipe for target 'dirs' failed
make: *** [dirs] Error 2

>

**Comment by mywave82** [comment]
It happens when you try to enable both SDL and SDL2 at the same time. I should block this possibility in the configure script.

**Comment by Csokis** [comment]
I used command ` ./configure --with-sdl2 --without-sdl` and it works perfectly. :) Thank you!

**Comment by mywave82** [comment]
configure script no longer allows both SDL 1.x and SDL 2.x at the same time
